name: Validate

permissions: {}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "24"

      - name: Install yarn
        shell: bash
        run: |
          set -euo pipefail
          corepack enable && corepack prepare yarn@4 --activate

      - name: Install dependencies
        shell: bash
        run: |
          set -euo pipefail
          yarn install

      - name: Build assets
        shell: bash
        run: |
          set -euo pipefail
          yarn build

      - name: Check for changes
        shell: bash
        run: |
          set -euo pipefail
          git diff --exit-code --name-status

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          cache: false
          go-version: "1.25.x"

      - name: Test embedded assets
        shell: bash
        run: |
          set -euo pipefail
          go test ./...
